import { useState, createContext } from 'react';
import marcos01 from '../assets/img/jogadores/1-marcos.jpg';
import cafu02 from '../assets/img/jogadores/2-cafu.jpg';
import lucio03 from '../assets/img/jogadores/3-lucio.jpg';
import roque04 from '../assets/img/jogadores/4-roquejr.jpg';
import edmilson05 from '../assets/img/jogadores/5-edmilson.jpg';
import rcarlos06 from '../assets/img/jogadores/6-robertocarlos.jpg';
import gilberto08 from '../assets/img/jogadores/8-gilbertosilva.jpg';
import ronaldo09 from '../assets/img/jogadores/9-ronaldo.jpg';
import rivaldo10 from '../assets/img/jogadores/10-rivaldo.jpg';
import ronaldinho11 from '../assets/img/jogadores/11-ronaldinho.jpg';
import kleberson15 from '../assets/img/jogadores/15-kleberson.jpg';
import tecfelipao from '../assets/img/jogadores/tec-felipao.jpg';

export const ElencoContext = createContext({});

export default function ElencoProvider({children}){
    const [jogadores, setJogadores] = useState([
        {id: 1, nome: 'Marcos', camisa: '01', posicao: 'goleiro', foto: marcos01, partidas: '7', gols: '0', biografia: 'Marcos Roberto Silveira Reis, mais conhecido apenas como Marcos (Oriente, 4 de agosto de 1973), é um ex-futebolista brasileiro que atuava como goleiro. Marcos iniciou a sua carreira jogando pelas categorias de base do Lençoense até 1992, quando se transferiu para o Palmeiras e tornou-se atleta profissional. O goleiro então passou a sua carreira inteira como atleta do Palmeiras; vestiu a camisa alviverde de 1992 a 2012.'},
        {id: 2, nome: 'Cafu', camisa: '02', posicao: 'lateral', foto: cafu02, partidas: '7', gols: '0', biografia: 'Marcos Evangelista de Morais (Itaquaquecetuba, 7 de junho de 1970), mais conhecido como Cafu, é um ex-futebolista brasileiro que atuava com lateral-direito. É considerado por muitos como um dos maiores laterais direitos da história do futebol. Ele é o recordista de jogos pela Seleção Brasileira de Futebol Masculino, com 149 partidas. Fez parte das equipes vencedoras das Copas do Mundo de 1994 e 2002, além das copas de 1998 e 2006.'},
        {id: 3, nome: 'Lúcio', camisa: '03', posicao: 'zagueiro', foto: lucio03, partidas: '7', gols: '0', biografia: 'Lucimar da Silva Ferreira, mais conhecido apenas como Lúcio (Planaltina, 8 de maio de 1978), é um ex-futebolista brasileiro que atuava como zagueiro. Foi um jogador conhecido pela sua força física, pelo seu jogo aéreo e pela sua presença no ataque, o que lhe rendeu a marca de 52 gols marcados na carreira. Quase uma unanimidade entre os torcedores e especialistas brasileiros, Lúcio é o quinto jogador que mais vezes vestiu a camisa da Seleção Brasileira, com 105 presenças, além de ter sido o capitão da equipe canarinha na Copa do Mundo FIFA de 2010 e na Copa América de 2011.'},
        {id: 4, nome: 'Roque Júnior', camisa: '04', posicao: 'zagueiro', foto: roque04, partidas: '6', gols: '0', biografia: 'José Vítor Roque Júnior, mais conhecido como Roque Jr. (Santa Rita do Sapucaí, 31 de agosto de 1976), é um ex-futebolista brasileiro e treinador que atuou como zagueiro. Roque Jr. foi titular da Seleção Brasileira no título da Copa do Mundo de 2002.'},
        {id: 5, nome: 'Edmilson', camisa: '05', posicao: 'zagueiro', foto: edmilson05, partidas: '6', gols: '1', biografia: 'José Edmílson Gomes de Moraes (Taquaritinga, 10 de julho de 1976), mais conhecido como Edmílson, é um ex-futebolista brasileiro que atuava como volante e zagueiro. Atualmente é presidente do Futebol Clube SKA Brasil. Durante sua carreira conquistou os dois maiores campeonatos do planeta: a Copa do Mundo em 2002 e a UEFA Champions League em 2006 jogando pelo Barcelona. Aposentou-se em 2012.'},
        {id: 6, nome: 'Roberto Carlos', camisa: '06', posicao: 'lateral', foto: rcarlos06, partidas: '6', gols: '1', biografia: 'Roberto Carlos da Silva Rocha, mais conhecido apenas como Roberto Carlos (Garça, 10 de abril de 1973), é um ex-futebolista brasileiro que atuava como lateral-esquerdo. É considerado por alguns como o melhor de sua geração na posição, e também o lateral-esquerdo mais ofensivo da história.'},
        {id: 7, nome: 'Gilberto Silva', camisa: '08', posicao: 'volante', foto: gilberto08, partidas: '7', gols: '0', biografia: 'Gilberto Aparecido da Silva, mais conhecido como Gilberto Silva (Lagoa da Prata, 7 de outubro de 1976), é um ex-futebolista brasileiro que atuava como volante. Iniciou sua carreira em 1997, no América Mineiro e sua boa performance rendeu-lhe um contrato com o Atlético Mineiro no ano 2000. Ele se tornou um dos principais jogadores da equipe, defendendo-a por três anos no campeonato brasileiro. Ganhou notoriedade fazendo parte da seleção que conquistou a Copa do Mundo de 2002, atuando em todas as sete partidas disputadas pelo Brasil.'},
        {id: 8, nome: 'Ronaldo', camisa: '09', posicao: 'atacante', foto: ronaldo09, partidas: '7', gols: '8', biografia: 'Ronaldo Luís Nazário de Lima, mais conhecido como Ronaldo, Ronaldo Fenômeno ou simplesmente Fenômeno (Rio de Janeiro, 22 de setembro de 1976), é um empresário e ex-futebolista brasileiro que atuava como atacante, amplamente reconhecido como um dos melhores futebolistas de todos os tempos. Atualmente é presidente do Real Valladolid, da Espanha, e sócio-proprietário do Cruzeiro, do Brasil. Foi eleito o Melhor Jogador do Mundo pela FIFA em 1996, 1997 e 2002.'},
        {id: 9, nome: 'Rivaldo', camisa: '10', posicao: 'atacante', foto: rivaldo10, partidas: '7', gols: '5', biografia: 'Rivaldo Vítor Borba Ferreira, mais conhecido apenas como Rivaldo (Recife, 19 de abril de 1972), é um ex-futebolista brasileiro que atuava como meio-campista. É considerado por muitos o maior meia e um dos maiores jogadores do futebol mundial nos últimos tempos, e integra o grupo dos "4Rs" (Ronaldo, Romário, Ronaldinho Gaúcho e Rivaldo), estes considerados os quatro melhores jogadores brasileiros da história recente do futebol. Ídolo no Barcelona, onde sua atuação fez com que fosse eleito o melhor jogador do mundo pela FIFA em 1999, foi decisivo para a Seleção Brasileira conquistar seu quinto título mundial na competição disputada na Coreia do Sul e no Japão em 2002.'},
        {id: 10, nome: 'Ronaldinho', camisa: '11', posicao: 'meia', foto: ronaldinho11, partidas: '5', gols: '2', biografia: 'Ronaldo de Assis Moreira, mais conhecido como Ronaldinho Gaúcho ou simplesmente Ronaldinho (Porto Alegre, 21 de março de 1980), é um ex-futebolista brasileiro que atuava como meia-atacante. Atualmente é embaixador do Barcelona, clube em que fez história. Venceu o prêmio Melhor Jogador do Mundo pela FIFA em 2004 e 2005, época em que viveu o grande auge de sua carreira. Foi o primeiro (e ainda é o único) futebolista na história a ter conquistado Liga dos Campeões da UEFA, a Libertadores, a Copa do Mundo e a também ter sido eleito o Melhor do Mundo.'},
        {id: 11, nome: 'Kleberson', camisa: '15', posicao: 'volante', foto: kleberson15, partidas: '5', gols: '0', biografia: 'José Kléberson Pereira, mais conhecido apenas como Kléberson (Uraí, 19 de junho de 1979), é um ex-futebolista brasileiro que atuava como volante ou meio-campista. Ganhador do prêmio Bola de Prata da ESPN de 2001, Kléberson fez parte do plantel da Seleção Brasileira que foi campeão do mundo em 2002.'},
        {id: 12, nome: 'Luiz Felipe Scolari', camisa: '', posicao: 'técnico', foto: tecfelipao, partidas: '7', gols: '0', biografia: 'Luiz Felipe Scolari, também conhecido apenas como Scolari ou Felipão (Passo Fundo, 9 de novembro de 1948), é um treinador e ex-futebolista brasileiro que atuava como zagueiro. Foi campeão do mundo de futebol como técnico da Seleção Brasileira em 2002 na Copa do Mundo do Japão e Coreia do Sul. Entre os clubes que treinou, teve importantes e vitoriosas passagens por Grêmio e Palmeiras, com os quais conquistou a Copa Libertadores da América. Em 2013, foi campeão da Copa das Confederações pela Seleção Brasileira.'}
    ]);

    return(
        <ElencoContext.Provider value={{jogadores, setJogadores}}>
            {children}
        </ElencoContext.Provider>
    );
}